# Diabetes Prediction

In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("All libraries are imported")

All libraries are imported

In [37]:
# To read the dataset with pandas library.
df = pd.read_csv("E:/ethans-tech-datascience/Advanced_Data_Analytics_Projects/Diabetes_Prediction/dataset/Diabetes_prediction.csv")
df.head(5)

,EmployeeName,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,NATHANIEL FORD,Female,80.0,0,1,never,25.19,6.6,140,0
1,GARY JIMENEZ,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,ALBERT PARDINI,Male,28.0,0,0,never,27.32,5.7,158,0
3,CHRISTOPHER CHONG,Female,36.0,0,0,current,23.45,5.0,155,0
4,PATRICK GARDNER,Male,76.0,1,1,current,20.14,4.8,155,0

In [38]:
# To know the information of the dataset i.e., column and its type.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   EmployeeName         100000 non-null  str
 1   gender               100000 non-null  str
 2   age                  100000 non-null  float64
 3   hypertension         100000 non-null  int64
 4   heart_disease        100000 non-null  int64
 5   smoking_history      100000 non-null  str
 6   bmi                  100000 non-null  float64
 7   HbA1c_level          100000 non-null  float64
 8   blood_glucose_level  100000 non-null  int64
 9   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), str(3)
memory usage: 7.6 MB

In [39]:
# To get statistical description of the above dataset briefly.
df.describe()

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
count,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,41.885856,0.07485,0.039420,27.320767,5.527507,138.058060,0.085000
std,22.516840,0.26315,0.194593,6.636783,1.070672,40.708136,0.278883
min,0.080000,0.00000,0.000000,10.010000,3.500000,80.000000,0.000000
25%,24.000000,0.00000,0.000000,23.630000,4.800000,100.000000,0.000000
50%,43.000000,0.00000,0.000000,27.320000,5.800000,140.000000,0.000000
75%,60.000000,0.00000,0.000000,29.580000,6.200000,159.000000,0.000000
max,80.000000,1.00000,1.000000,95.690000,9.000000,300.000000,1.000000

In [40]:
# To find null value exist or not.
df.isnull().sum()

EmployeeName           0
gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [41]:
# To know how many rows and columns in presented dataset.
df.shape

(100000, 10)

In [42]:
df

,EmployeeName,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,NATHANIEL FORD,Female,80.0,0,1,never,25.19,6.6,140,0
1,GARY JIMENEZ,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,ALBERT PARDINI,Male,28.0,0,0,never,27.32,5.7,158,0
3,CHRISTOPHER CHONG,Female,36.0,0,0,current,23.45,5.0,155,0
4,PATRICK GARDNER,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...,...
99995,William Chun,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Antoinette L Wells,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Richard D Swart,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Vivian Chu,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Savitree Satram,Female,57.0,0,0,current,22.43,6.6,90,0

In [43]:
df['EmployeeName'] = df['EmployeeName'].str.capitalize()
df[['EmployeeName']].head(5)

        EmployeeName
0     Nathaniel ford
1       Gary jimenez
2     Albert pardini
3  Christopher chong
4    Patrick gardner

In [44]:
# Creating a new column age_group

conditions = [
    df['age'] <= 18,
    df['age'] <= 30,
    df['age'] <= 45,
    df['age'] <= 60
]

choices = [
    'Below 18',
    '19-30',
    '31-45',
    '46-60'
]

df['Age_Group'] = np.select(
    conditions,
    choices,
    default='Above 61'
)

df[['age', 'Age_Group']].head(10)

    age Age_Group
0  80.0  Above 61
1  54.0     46-60
2  28.0     19-30
3  36.0     31-45
4  76.0  Above 61
5  20.0     19-30
6  44.0     31-45
7  79.0  Above 61
8  42.0     31-45
9  32.0     31-45

In [48]:
# Converting float value of age into int value.
df['age'] = df['age'].astype(int)
df[['age']].head(7)

   age
0   80
1   54
2   28
3   36
4   76
5   20
6   44

In [49]:
df.head(5)

,EmployeeName,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes,Age_Group
0,Nathaniel ford,Female,80,0,1,never,25.19,6.6,140,0,Above 61
1,Gary jimenez,Female,54,0,0,No Info,27.32,6.6,80,0,46-60
2,Albert pardini,Male,28,0,0,never,27.32,5.7,158,0,19-30
3,Christopher chong,Female,36,0,0,current,23.45,5.0,155,0,31-45
4,Patrick gardner,Male,76,1,1,current,20.14,4.8,155,0,Above 61